### ISSUE TITLE
Add MailHog service

### ISSUE THREAD

**Issue by DevMoath** [DevMoath/docker-compose-laravel#1]
```
mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
        - 1025:1025
        - 8025:8025
    networks:
        - laravel
```
